// Design ids are uuids generated by Postgres (`designs.id default
// gen_random_uuid()`), so nothing here mints them any more — we only validate
// what arrives in a URL before spending a database round-trip on it.
//
// The uuid is the only access control on a by-id read (see api/designs/[id].js):
// 122 bits of entropy, unguessable, and never enumerated anywhere.
export const DESIGN_ID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
